### ISSUE TITLE
Ejercicio InteraccionHTML

### ISSUE THREAD

**Issue by CristinaPicazo** [CristinaPicazo/practica_dwec_gestor_presupuesto#1]
Ejercicio terminado @pedroprieto, muchas gracias

**Comment by pedroprieto** [comment]
Buenas, Cristina,

Tienes varios fallos en el test 4. ¿Puedes revisarlo y hacer la PR cuando lo tengas?

Si tienes alguna duda y quieres que te eche una mano, dímelo sin problema :wink: 

Un saludo!

**Comment by CristinaPicazo** [comment]
Ahora si, perdona @pedroprieto que no me había dado cuenta del test.

**Comment by pedroprieto** [comment]
Bien hecho :muscle: !! Acuérdate en las siguientes de hacer la Pull Request :wink:

**Comment by CristinaPicazo** [comment]
ejercicio resuelto

**Comment by pedroprieto** [comment]
Buen trabajo! Todo perfecto! :clap:

Acuérdate de hacer las entregas por Pull Request, no por issue. Un saludo!!
